(function (global) {
  if (global.GMXExtConfig) return;

  const EXT_WP_NAMES = [
  "Geometric Scene",
  "Abstract Scene",
  "Neon Scene",
  "Neon Scene 2",
  "Neon Scene 3",
  "Geometric Scene 2",
  "Neon Scene 4",
  "Neon Scene 5",
  "Geometric Scene 3",
  "Neon Scene 6",
  "Abstract Scene 2",
  "Abstract Scene 3",
  "Neon Scene 7",
  "Neon Scene 8",
  "Futuristic Scene",
  "Night Scene",
  "Minimal Scene",
  "Minimal Scene 2",
  "Futuristic Scene 2",
  "Futuristic Scene 3",
  "Geometric Scene 4",
  "Abstract Scene 4",
  "Forest Scene",
  "Futuristic Scene 4",
  "Night Scene 2",
  "Forest Scene 2",
  "Minimal Scene 3",
  "Forest Scene 3",
  "Abstract Scene 5",
  "Futuristic Scene 5",
  "Futuristic Scene 6",
  "Futuristic Scene 7",
  "Forest Scene 4",
  "Forest Scene 5",
  "Geometric Scene 5",
  "Space Scene",
  "Futuristic Scene 8",
  "Mountains Scene",
  "Mountains Scene 2",
  "Night Scene 3",
  "Abstract Scene 6",
  "Moon Scene",
  "Geometric Scene 6",
  "Mountains Scene 3",
  "Forest Scene 6",
  "Desert Scene",
  "Ocean Scene",
  "Desert Scene 2",
  "Abstract Scene 7",
  "Ocean Scene 2",
  "Geometric Scene 7",
  "Night Scene 4",
  "Moon Scene 2",
  "Forest Scene 7",
  "Moon Scene 3",
  "Moon Scene 4",
  "Moon Scene 5",
  "Forest Scene 8",
  "Abstract Scene 8",
  "Forest Scene 9",
  "Desert Scene 3",
  "Mountains Scene 4",
  "Night Scene 5",
  "Night Scene 6",
  "Desert Scene 4",
  "Northern Scene",
  "Space Scene 2",
  "Desert Scene 5",
  "Desert Scene 6",
  "Night Scene 7",
  "Minimal Scene 4",
  "Mountains Scene 5",
  "Mountains Scene 6",
  "Mountains Scene 7",
  "Ocean Scene 3",
  "Space Scene 3",
  "Mountains Scene 8",
  "Minimal Scene 5",
  "Minimal Scene 6",
  "Mountains Scene 9",
  "Ocean Scene 4",
  "Minimal Scene 7",
  "Ocean Scene 5",
  "Space Scene 4",
  "Space Scene 5",
  "Space Scene 6",
  "Northern Scene 2",
  "Space Scene 7",
  "Space Scene 8",
  "Ocean Scene 6",
  "Northern Scene 3",
  "Northern Scene 4",
  "Ocean Scene 7",
  "Ocean Scene 8",
  "Northern Scene 5",
  "Northern Scene 6",
  "Northern Scene 7",
  "Ocean Scene 9",
  "Moon Scene 6",
  "Moon Scene 7"
];

  const EXT_WALLPAPER_OPTIONS = (() => {
    const out = [
      { id: "ext_free_01", name: "Soft Gradient" },
      { id: "ext_free_02", name: "Calm Glow" },
    ];
    for (let i = 1; i <= 100; i++) {
      const n = String(i).padStart(2, "0");
      out.push({ id: `w${n}`, name: EXT_WP_NAMES[i - 1] || `Scene ${i}` });
    }
    return out;
  })();

  global.GMXExtConfig = {
    DEFAULT_BASE: "https://www.gmxreply.com",
    STORAGE_KEYS: {
      base: "gmx_ext_api_base_v2",
      handle: "gmx_ext_handle_v2",
      token: "gmx_ext_token_v2",
      mode: "gmx_ext_mode_v2",
      lastText: "gmx_ext_last_text_v2",
    },
    BANK_KEYS: {
      gm: "gmx_ext_bank_gm_v1",
      gn: "gmx_ext_bank_gn_v1",
      syncedAt: "gmx_ext_bank_synced_at_v1",
    },
    EXT_VERSION: "1.2.1",
    ALERT_KEYS: {
      enabled: "gmx_market_alerts_enabled_v1",
      interval: "gmx_market_alerts_interval_v1",
    },
    ASSET_REV: "20260626b",
    WALLPAPER_REFRESH_KEY: "gmx_ext_wp_refresh_20260323",
    LEGACY_KEYS: {
      base: "apiBase",
      handle: "handle",
      token: "token",
    },
    THEME_KEYS: {
      extTheme: "gmx_ext_theme_v2",
      siteTheme: "gmx_theme",
      extView: "gmx_ext_view_v2",
      extWallpaper: "gmx_ext_wp_v2",
      extWallpaperPopup: "gmx_ext_wp_v2_popup",
      extWallpaperQuick: "gmx_ext_wp_v2_quick",
      extCustomBg: "gmx_ext_custom_bg_global_v2",
    },
    LEGACY_THEME_KEYS: {
      extTheme: "gmx_ext_theme",
      extView: "gmx_ext_view",
      extWallpaper: "gmx_ext_wp",
      extWallpaperPopup: "gmx_ext_wp_view_popup",
      extWallpaperQuick: "gmx_ext_wp_view_quick",
      extCustomBg: "gmx_ext_custom_bg_global",
    },
    EXT_WP_NAMES,
    EXT_WALLPAPER_OPTIONS,
    DEFAULT_THEME: {
      id: "classic",
      a: "rgba(110,231,255,1)",
      b: "rgba(79,70,229,1)",
    },
    FALLBACK_LINES: {
      gm: [
        "gm, hope your day starts easy",
        "good morning, nice read here",
        "gm, strong post and a clean start",
        "gm, hope the morning treats you well",
        "good morning, this was a solid read",
        "gm, wishing you a smooth day ahead",
      ],
      gn: [
        "gn, hope you get a calm reset tonight",
        "good night, soft close here",
        "gn, rest well after this one",
        "good night, hope you get an easy reset",
        "gn, calm post to end the day on",
        "good night, sleep well tonight",
      ],
    },
  };
})(typeof globalThis !== "undefined" ? globalThis : window);
