(function (global) {
  if (global.GMXExtConfig) return;

  const EXT_WP_NAMES = [
  "BTC Stock Chart",
  "Gold Bitcoin",
  "Comic Hero Pages",
  "Alpine Aurora",
  "Blockchain Pulse",
  "Ethereum Pulse",
  "DeFi Pulse",
  "Web3 Pulse",
  "Token Pulse",
  "Satoshi Pulse",
  "Altcoin Pulse",
  "Fintech Pulse",
  "Bitcoin Glow",
  "Crypto Glow",
  "Blockchain Glow",
  "Ethereum Glow",
  "DeFi Glow",
  "Web3 Glow",
  "Token Glow",
  "Satoshi Glow",
  "Altcoin Glow",
  "Fintech Glow",
  "Bitcoin Night",
  "Crypto Night",
  "Blockchain Night",
  "Ethereum Night",
  "DeFi Night",
  "Neo Tokyo Pulse",
  "Cyber Pulse",
  "Shinjuku Pulse",
  "Akihabara Pulse",
  "Neon Alley Pulse",
  "Vaporwave Pulse",
  "Otaku Pulse",
  "Sakura Night Pulse",
  "Blade Runner Pulse",
  "Synth City Pulse",
  "Neo Tokyo Glow",
  "Cyber Glow",
  "Shinjuku Glow",
  "Akihabara Glow",
  "Neon Alley Glow",
  "Vaporwave Glow",
  "Otaku Glow",
  "Sakura Night Glow",
  "Blade Runner Glow",
  "Synth City Glow",
  "Neo Tokyo Night",
  "Cyber Night",
  "Shinjuku Night",
  "Akihabara Night",
  "Neon Alley Night",
  "Marvel Pulse",
  "Comic Pulse",
  "Avenger Pulse",
  "Super Pulse",
  "Shield Pulse",
  "Cape Pulse",
  "Origin Pulse",
  "Power Pulse",
  "Action Pulse",
  "Hero Glow",
  "Marvel Glow",
  "Comic Glow",
  "Avenger Glow",
  "Super Glow",
  "Shield Glow",
  "Cape Glow",
  "Origin Glow",
  "Power Glow",
  "Action Glow",
  "Neon Pulse",
  "City Pulse Pulse",
  "Skyline Pulse",
  "Urban Pulse",
  "Night Drive Pulse",
  "Metro Pulse",
  "Harbor Pulse",
  "Chrome Pulse",
  "Neon Glow",
  "City Pulse Glow",
  "Skyline Glow",
  "Urban Glow",
  "Night Drive Glow",
  "Metro Glow",
  "Harbor Glow",
  "Alpine Pulse",
  "Ocean Pulse",
  "Golden Pulse",
  "Nordic Pulse",
  "Glacier Pulse",
  "Misty Pulse",
  "Coastal Pulse",
  "Desert Pulse",
  "Silk Clouds Pulse",
  "Aurora Glow",
  "Alpine Glow",
  "Ocean Glow",
  "Golden Glow",
  "Nordic Glow"
];

  const EXT_WALLPAPER_OPTIONS = (() => {
    const out = [
      { id: "ext_free_01", name: "Soft Gradient" },
      { id: "ext_free_02", name: "Calm Glow" },
    ];
    for (let i = 1; i <= 100; i++) {
      const n = String(i).padStart(2, "0");
      out.push({ id: `w${n}`, name: EXT_WP_NAMES[i - 1] || `Scene ${i}` });
    }
    return out;
  })();

  global.GMXExtConfig = {
    DEFAULT_BASE: "https://www.gmxreply.com",
    STORAGE_KEYS: {
      base: "gmx_ext_api_base_v2",
      handle: "gmx_ext_handle_v2",
      token: "gmx_ext_token_v2",
      mode: "gmx_ext_mode_v2",
      lastText: "gmx_ext_last_text_v2",
    },
    ALERT_KEYS: {
      enabled: "gmx_market_alerts_enabled_v1",
      interval: "gmx_market_alerts_interval_v1",
    },
    ASSET_REV: "20260626b",
    WALLPAPER_REFRESH_KEY: "gmx_ext_wp_refresh_20260323",
    LEGACY_KEYS: {
      base: "apiBase",
      handle: "handle",
      token: "token",
    },
    THEME_KEYS: {
      extTheme: "gmx_ext_theme_v2",
      siteTheme: "gmx_theme",
      extView: "gmx_ext_view_v2",
      extWallpaper: "gmx_ext_wp_v2",
      extWallpaperPopup: "gmx_ext_wp_v2_popup",
      extWallpaperQuick: "gmx_ext_wp_v2_quick",
      extCustomBg: "gmx_ext_custom_bg_global_v2",
    },
    LEGACY_THEME_KEYS: {
      extTheme: "gmx_ext_theme",
      extView: "gmx_ext_view",
      extWallpaper: "gmx_ext_wp",
      extWallpaperPopup: "gmx_ext_wp_view_popup",
      extWallpaperQuick: "gmx_ext_wp_view_quick",
      extCustomBg: "gmx_ext_custom_bg_global",
    },
    EXT_WP_NAMES,
    EXT_WALLPAPER_OPTIONS,
    DEFAULT_THEME: {
      id: "classic",
      a: "rgba(110,231,255,1)",
      b: "rgba(79,70,229,1)",
    },
    FALLBACK_LINES: {
      gm: [
        "gm, hope your day starts easy",
        "good morning, nice read here",
        "gm, strong post and a clean start",
        "gm, hope the morning treats you well",
        "good morning, this was a solid read",
        "gm, wishing you a smooth day ahead",
      ],
      gn: [
        "gn, hope you get a calm reset tonight",
        "good night, soft close here",
        "gn, rest well after this one",
        "good night, hope you get an easy reset",
        "gn, calm post to end the day on",
        "good night, sleep well tonight",
      ],
    },
  };
})(typeof globalThis !== "undefined" ? globalThis : window);
