export type ArcadeGameKey = "neon" | "payload" | "steel" | "star" | "boss" | "rift" | "metro" | "void" | "gravity" | "ember" | "prism" | "thermal" | "sky" | "glass" | "quarry" | "drift" | "bloom" | "echo" | "vale" | "anchor" | "shunt" | "moss" | "ion" | "citadel" | "tower" | "deep" | "signal" | "harbor" | "warden" | "flare";
export type ReactArcadeGameKey = "rift" | "metro" | "void" | "gravity" | "ember" | "prism" | "thermal" | "sky" | "glass" | "quarry" | "drift" | "bloom" | "echo" | "vale" | "anchor" | "shunt" | "moss" | "ion" | "citadel" | "tower" | "deep" | "signal" | "harbor" | "warden" | "flare";

export type SaveMode = "none" | "local_now" | "supabase_next";

export interface ArcadeGameDef {
  key: ArcadeGameKey;
  title: string;
  access: "free" | "pro";
  highlight?: "showcase" | "top_pro";
  genre: string;
  session: string;
  saveMode: SaveMode;
  summary: string;
}

export interface ArcadeConceptDef {
  slug: string;
  title: string;
  genre: string;
  pitch: string;
  whyItFits: string;
  imagePath: string;
  reference: string;
}

export const CURRENT_GAMES: ArcadeGameDef[] = [
  {
    key: "neon",
    title: "Neon Strike",
    access: "free",
    genre: "top-down survivor shooter",
    session: "25-45+ min endless",
    saveMode: "none",
    summary: "Free anchor run with faster waves, longer pressure, and a React module that now writes into shared local ladders.",
  },
  {
    key: "payload",
    title: "Payload Lab",
    access: "pro",
    genre: "escort defense",
    session: "35-55 min route push",
    saveMode: "local_now",
    summary: "Long escort run with a React module, local checkpoints, and a clean upgrade path toward cloud resume.",
  },
  {
    key: "steel",
    title: "Steel Jaguar",
    access: "pro",
    genre: "run-and-gun platform rush",
    session: "40-60 min stage",
    saveMode: "local_now",
    summary: "Long side-scroll stage with local resume and a React module tied into shared local ladders.",
  },
  {
    key: "star",
    title: "Star Spark",
    access: "pro",
    genre: "combo survival",
    session: "45-60 min score run",
    saveMode: "local_now",
    summary: "Long score loop with local resume, a React live module, and shared local ladders.",
  },
  {
    key: "boss",
    title: "Boss Vault",
    access: "pro",
    genre: "boss-rush gauntlet",
    session: "35-55 min multi-room clear",
    saveMode: "local_now",
    summary: "Room-based boss ladder with a React live module, room checkpoints, and deeper local resume exports.",
  },
];

export const LIVE_REACT_GAMES: ArcadeGameDef[] = [
  {
    key: "rift",
    title: "Rift Harvest",
    access: "free",
    highlight: "showcase",
    genre: "survivor arena",
    session: "20-40 min scaling run",
    saveMode: "none",
    summary: "Free showcase survivor run with auto-fire, shard pickups, elite waves, short Rift Surge windows, and the strongest first-hit preview of the React-only arcade layer.",
  },
  {
    key: "void",
    title: "Void Drift",
    access: "free",
    genre: "lane runner / dodge",
    session: "10-35 min speed climb",
    saveMode: "none",
    summary: "Fast free lane runner built for mastery loops: swap lanes, grab flux gates for shields, and survive the redline.",
  },
  {
    key: "gravity",
    title: "Gravity Loop",
    access: "free",
    genre: "orbital survival racer",
    session: "12-35 min rising loop",
    saveMode: "none",
    summary: "Free orbital survival racer with ring shifts, gate pickups, and a clean high-speed loop that still feels premium in short sessions.",
  },
  {
    key: "drift",
    title: "Drift Relay",
    access: "free",
    genre: "vector relay escort",
    session: "16-42 min crosswind hold",
    saveMode: "none",
    summary: "Free relay escort with auto-pings, burst sweeps, crosswind pulses, storm corridors, and a longer skill-forward free session.",
  },
  {
    key: "moss",
    title: "Moss Static",
    access: "free",
    genre: "canopy static trim",
    session: "18-54 min hedge hold",
    saveMode: "none",
    summary: "Free canopy-static run with hedge trims, routed moss pressure, static field swings, and a calm but sticky long-run hook.",
  },
  {
    key: "flare",
    title: "Flare Dock",
    access: "pro",
    highlight: "top_pro",
    genre: "dock flare routing",
    session: "18-44 min burn-grid hold",
    saveMode: "none",
    summary: "Top-tier Pro dock-pressure module with vent sweeps, coolant tank recoveries, flare-wall spikes, and a clearer overdrive chain that makes the premium hold loop feel heavier.",
  },
  {
    key: "signal",
    title: "Signal Cartel",
    access: "pro",
    highlight: "top_pro",
    genre: "route hijack defense",
    session: "18-42 min relay hold",
    saveMode: "none",
    summary: "Top-tier Pro route defense with lane commands, jammer charges, blackout surges, cartel windows, and a sharper flagship hijack-control rhythm.",
  },
  {
    key: "deep",
    title: "Deep Salvage",
    access: "pro",
    highlight: "top_pro",
    genre: "submersible risk run",
    session: "18-45 min extraction dive",
    saveMode: "none",
    summary: "Top-tier Pro extraction dive with oxygen debt, hull pressure, abyss-current windows, beacon banking, and a heavier flagship pressure-dive identity.",
  },
  {
    key: "anchor",
    title: "Anchor Rift",
    access: "pro",
    highlight: "top_pro",
    genre: "anchor hold / surge release",
    session: "18-50 min fracture hold",
    saveMode: "none",
    summary: "Top-tier Pro anchor-pressure run with surge vents, crack bands, charge recovery, rift-pulse windows, and a heavier flagship long-session identity.",
  },
  {
    key: "echo",
    title: "Echo Verge",
    access: "pro",
    highlight: "top_pro",
    genre: "mirror-lane echo hold",
    session: "16-46 min verge climb",
    saveMode: "none",
    summary: "Top-tier Pro mirror-lane hold with echo sweeps, cache recovery, rupture bands, and a strong mid-run phase identity.",
  },
  {
    key: "metro",
    title: "Metro Surge",
    access: "pro",
    highlight: "top_pro",
    genre: "line routing / panic management",
    session: "15-35 min escalating defense",
    saveMode: "none",
    summary: "Premium line-routing run focused on mouse-only dispatch, reserve banking, line repairs, and rising overload spikes.",
  },
  {
    key: "harbor",
    title: "Harbor Null",
    access: "pro",
    genre: "dock defense scramble",
    session: "18-44 min harbor hold",
    saveMode: "none",
    summary: "Premium dock defense run with pulse charge, breaker skiffs, battery caches, support drops, and a longer lane-hold loop.",
  },
  {
    key: "warden",
    title: "Warden Pulse",
    access: "pro",
    genre: "relay sentry climb",
    session: "18-42 min relay hold",
    saveMode: "none",
    summary: "Premium sentry defense module with four pulse arcs, overclock sweeps, breaker packets, and a denser relay hold loop.",
  },
  {
    key: "ion",
    title: "Ion Switch",
    access: "pro",
    genre: "grid reroute scramble",
    session: "18-44 min relay reroute",
    saveMode: "none",
    summary: "Premium reroute module with four ion nodes, manual route flips, purge sweeps, and a denser stability loop.",
  },
  {
    key: "citadel",
    title: "Citadel Breach",
    access: "pro",
    genre: "siege defense",
    session: "18-40 min lane hold",
    saveMode: "none",
    summary: "Premium siege defense module with lane volleys, elite breach waves, and a clean lane-pressure hook.",
  },
  {
    key: "tower",
    title: "Tower Hex",
    access: "pro",
    genre: "hex defense climb",
    session: "16-38 min sector hold",
    saveMode: "none",
    summary: "Premium tower defense loop with rotating sectors, pulse charges, and a stronger midcore hold profile.",
  },
  {
    key: "vale",
    title: "Pulse Vale",
    access: "pro",
    genre: "soft-lane pulse hold",
    session: "16-48 min basin climb",
    saveMode: "none",
    summary: "Premium soft-lane hold with pulse sweeps, basin phases, cache recovery, and a smoother high-retention climb.",
  },
  {
    key: "shunt",
    title: "Shunt Garden",
    access: "pro",
    genre: "signal garden routing",
    session: "18-52 min canopy hold",
    saveMode: "none",
    summary: "Premium signal-garden run with canopy spread, route bloom windows, charge recovery, and a dense routing identity.",
  },
  {
    key: "glass",
    title: "Glass Frontier",
    access: "pro",
    genre: "shield corridor run",
    session: "14-38 min mirror hold",
    saveMode: "none",
    summary: "Premium shield corridor run with focus-lane shifting, mirror surges, charge-cell recoveries, and a sharper defense rhythm.",
  },
  {
    key: "quarry",
    title: "Pulse Quarry",
    access: "pro",
    genre: "pulse mining sprint",
    session: "14-40 min quarry push",
    saveMode: "none",
    summary: "Premium mining run with pulse cuts, charge recovery cells, quake surges, and a heavier lane-pressure cadence.",
  },
  {
    key: "bloom",
    title: "Vector Bloom",
    access: "pro",
    genre: "split-lane bloom defense",
    session: "16-44 min canopy hold",
    saveMode: "none",
    summary: "Premium bloom-defense variant with canopy bands, dew cache recovery, split gust spikes, and cleaner pressure stacking.",
  },
  {
    key: "ember",
    title: "Ember Rail",
    access: "pro",
    genre: "convoy defense sprint",
    session: "14-35 min sector escort",
    saveMode: "none",
    summary: "Premium convoy run with armed tracks, cargo leaks, and rising sector heat for a denser escort rhythm.",
  },
  {
    key: "prism",
    title: "Prism Courier",
    access: "pro",
    genre: "lane courier / burst runner",
    session: "12-34 min route chain",
    saveMode: "none",
    summary: "Premium courier run with lane swaps, burst routing, stabilizer pickups, and a cleaner high-APM route chain.",
  },
  {
    key: "thermal",
    title: "Thermal Drop",
    access: "pro",
    genre: "heatfall descent",
    session: "14-38 min cooling run",
    saveMode: "none",
    summary: "Premium descent run with heat spikes, coolant vents, depth pressure, and a tighter long-drop survival curve.",
  },
  {
    key: "sky",
    title: "Sky Heist",
    access: "pro",
    genre: "airlane raid run",
    session: "12-36 min convoy chase",
    saveMode: "none",
    summary: "Premium airlane raid with auto-fire passes, cargo boosts, patrol waves, and a wider high-speed chase loop.",
  },
];

export const NEXT_GAME_CONCEPTS: ArcadeConceptDef[] = [
  {
    slug: "lattice-ferry",
    title: "Lattice Ferry",
    genre: "lane ferry / fracture hold",
    pitch: "Guide a fragile lattice ferry through fracture lanes, bank calm windows, and hold a longer route under rising pulse drag.",
    whyItFits: "With Free capped at 5 live React slots, Lattice Ferry works best as the next premium-grade launch unless the showcase rotation gets intentionally swapped.",
    imagePath: "/docs/arcade_concepts/glass_frontier.svg",
    reference: "Long-form lane ferry pressure",
  },
  {
    slug: "cinder-span",
    title: "Cinder Span",
    genre: "heat bridge / vent hold",
    pitch: "Hold a cracked heat span together, vent flash pressure in timed bursts, and survive a slow collapse loop where each clean release widens the route for a few more seconds.",
    whyItFits: "Fits the new premium-heavy plan: one showcase-grade Free hook stays visible, while heavier long-session launches like this default to Pro.",
    imagePath: "/docs/arcade_concepts/flare_dock.svg",
    reference: "Vent-and-hold collapse rhythm",
  },
  {
    slug: "torrent-loom",
    title: "Torrent Loom",
    genre: "current weave / seam hold",
    pitch: "Weave a soft current loom through unstable seams, bank calm pockets, and keep the flow aligned as surge knots start snapping the weave apart.",
    whyItFits: "Keeps the roadmap aimed at stronger premium depth while the Free shelf stays deliberately tight and the React arcade layer stays clear.",
    imagePath: "/docs/arcade_concepts/signal_cartel.svg",
    reference: "Soft seam-weave pressure",
  },
];


export const ARCADE_COPYSET: string[] = [

  "frontend/src/pages/ArcadePage.tsx",
  "frontend/src/features/arcade/gameRegistry.ts",
  "frontend/src/features/arcade/storage.ts",
  "frontend/src/features/arcade/runtimeAdapter.ts",
  "frontend/src/features/arcade/migrationBundle.ts",
  "frontend/src/features/arcade/supabaseFoundation.ts",
  "frontend/src/features/arcade/supabaseGatewayScaffold.ts",
  "frontend/src/features/arcade/supabaseLiveMergePlan.ts",
  "frontend/src/components/arcade/NeonStrikeModule.tsx",
  "frontend/src/components/arcade/PayloadLabModule.tsx",
  "frontend/src/components/arcade/SteelJaguarModule.tsx",
  "frontend/src/components/arcade/StarSparkModule.tsx",
  "frontend/src/components/arcade/BossVaultModule.tsx",
  "frontend/src/components/arcade/RiftHarvestModule.tsx",
  "frontend/src/components/arcade/MetroSurgeModule.tsx",
  "frontend/src/components/arcade/VoidDriftModule.tsx",
  "frontend/src/components/arcade/GravityLoopModule.tsx",
  "frontend/src/components/arcade/EmberRailModule.tsx",
  "frontend/src/components/arcade/PrismCourierModule.tsx",
  "frontend/src/components/arcade/ThermalDropModule.tsx",
  "frontend/src/components/arcade/SkyHeistModule.tsx",
  "frontend/src/components/arcade/GlassFrontierModule.tsx",
  "frontend/src/components/arcade/PulseQuarryModule.tsx",
  "frontend/src/components/arcade/DriftRelayModule.tsx",
  "frontend/src/components/arcade/VectorBloomModule.tsx",
  "frontend/src/components/arcade/EchoVergeModule.tsx",
  "frontend/src/components/arcade/PulseValeModule.tsx",
  "frontend/src/components/arcade/AnchorRiftModule.tsx",
  "frontend/src/components/arcade/ShuntGardenModule.tsx",
  "frontend/src/components/arcade/MossStaticModule.tsx",
  "frontend/src/components/arcade/IonSwitchModule.tsx",
  "frontend/src/components/arcade/CitadelBreachModule.tsx",
  "frontend/src/components/arcade/TowerHexModule.tsx",
  "frontend/src/components/arcade/DeepSalvageModule.tsx",
  "frontend/src/components/arcade/SignalCartelModule.tsx",
  "frontend/src/components/arcade/HarborNullModule.tsx",
  "frontend/src/components/arcade/WardenPulseModule.tsx",
  "frontend/src/components/arcade/FlareDockModule.tsx",
  "frontend/src/components/arcade/ArcadeLeaderboardPanel.tsx",
  "frontend/src/features/arcade/modules/neonStrikeCore.ts",
  "frontend/src/features/arcade/modules/payloadLabCore.ts",
  "frontend/src/features/arcade/modules/steelJaguarCore.ts",
  "frontend/src/features/arcade/modules/starSparkCore.ts",
  "frontend/src/features/arcade/modules/bossVaultCore.ts",
  "frontend/src/features/arcade/modules/riftHarvestCore.ts",
  "frontend/src/features/arcade/modules/metroSurgeCore.ts",
  "frontend/src/features/arcade/modules/voidDriftCore.ts",
  "frontend/src/features/arcade/modules/gravityLoopCore.ts",
  "frontend/src/features/arcade/modules/emberRailCore.ts",
  "frontend/src/features/arcade/modules/prismCourierCore.ts",
  "frontend/src/features/arcade/modules/thermalDropCore.ts",
  "frontend/src/features/arcade/modules/skyHeistCore.ts",
  "frontend/src/features/arcade/modules/glassFrontierCore.ts",
  "frontend/src/features/arcade/modules/pulseQuarryCore.ts",
  "frontend/src/features/arcade/modules/driftRelayCore.ts",
  "frontend/src/features/arcade/modules/vectorBloomCore.ts",
  "frontend/src/features/arcade/modules/echoVergeCore.ts",
  "frontend/src/features/arcade/modules/pulseValeCore.ts",
  "frontend/src/features/arcade/modules/anchorRiftCore.ts",
  "frontend/src/features/arcade/modules/shuntGardenCore.ts",
  "frontend/src/features/arcade/modules/mossStaticCore.ts",
  "frontend/src/features/arcade/modules/ionSwitchCore.ts",
  "frontend/src/features/arcade/modules/citadelBreachCore.ts",
  "frontend/src/features/arcade/modules/towerHexCore.ts",
  "frontend/src/features/arcade/modules/deepSalvageCore.ts",
  "frontend/src/features/arcade/modules/signalCartelCore.ts",
  "frontend/src/features/arcade/modules/harborNullCore.ts",
  "frontend/src/features/arcade/modules/wardenPulseCore.ts",
  "frontend/src/features/arcade/modules/flareDockCore.ts",
  "frontend/src/main.tsx",
  "public/arcade.js",
  "frontend/public/arcade.js",
  "supabase/04_arcade_progress.sql",
  "supabase/05_arcade_runtime_sync_scaffold.sql",
  "supabase/06_arcade_runtime_queue_scaffold.sql",
  "supabase/07_arcade_runtime_rpc_scaffold.sql",
  "supabase/08_arcade_runtime_gateway_stub.sql",
  "docs/ARCADE_PHASE45_MASTER_HANDOFF_CHECKLIST_RU.txt",
  "docs/ARCADE_PHASE45_REACT_EXPANSION_README_RU.txt",
  "docs/ARCADE_PHASE45_QUICK_MIGRATION_COPYSET.txt",
  "docs/ARCADE_PHASE46_MASTER_HANDOFF_CHECKLIST_RU.txt",
  "docs/ARCADE_PHASE46_REACT_EXPANSION_README_RU.txt",
  "docs/ARCADE_PHASE46_QUICK_MIGRATION_COPYSET.txt",
  "docs/ARCADE_PHASE46_SETUP_AND_CONTINUATION_RU.txt",
  "docs/ARCADE_PHASE47_MASTER_HANDOFF_CHECKLIST_RU.txt",
  "docs/ARCADE_PHASE47_REACT_ACCESS_REBALANCE_README_RU.txt",
  "docs/ARCADE_PHASE47_QUICK_MIGRATION_COPYSET.txt",
  "docs/ARCADE_PHASE47_SETUP_AND_CONTINUATION_RU.txt",
  "docs/ARCADE_PHASE48_MASTER_HANDOFF_CHECKLIST_RU.txt",
  "docs/ARCADE_PHASE48_STABILIZATION_README_RU.txt",
  "docs/ARCADE_PHASE48_QUICK_MIGRATION_COPYSET.txt",
  "docs/ARCADE_PHASE48_SETUP_AND_CONTINUATION_RU.txt",
  "docs/ARCADE_PHASE48_PROJECT_STATUS_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE48_NEW_CHAT_START_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE48_QUICK_MIGRATION_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE48_ARCHITECTURE_RULES_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE45_NEW_CHAT_START_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE45_QUICK_MIGRATION_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE45_ARCHITECTURE_RULES_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE46_NEW_CHAT_START_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE46_QUICK_MIGRATION_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE46_ARCHITECTURE_RULES_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE47_NEW_CHAT_START_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE47_QUICK_MIGRATION_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE47_ARCHITECTURE_RULES_RU.txt",
  "docs/ARCADE_PHASE52_MASTER_HANDOFF_CHECKLIST_RU.txt",
  "docs/ARCADE_PHASE52_SUPABASE_FOUNDATION_README_RU.txt",
  "docs/ARCADE_PHASE52_QUICK_MIGRATION_COPYSET.txt",
  "docs/ARCADE_PHASE52_SETUP_AND_CONTINUATION_RU.txt",
  "docs/ARCADE_PHASE52_PROJECT_STATUS_RU.txt",
  "docs/ARCADE_PHASE53_MASTER_HANDOFF_CHECKLIST_RU.txt",
  "docs/ARCADE_PHASE53_SUPABASE_FOUNDATION_README_RU.txt",
  "docs/ARCADE_PHASE53_QUICK_MIGRATION_COPYSET.txt",
  "docs/ARCADE_PHASE53_SETUP_AND_CONTINUATION_RU.txt",
  "docs/ARCADE_PHASE53_PROJECT_STATUS_RU.txt",
  "docs/ARCADE_PHASE53_SUPABASE_LIVE_WIRING_PLAN_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE52_NEW_CHAT_START_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE52_QUICK_MIGRATION_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE52_ARCHITECTURE_RULES_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE53_NEW_CHAT_START_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE53_QUICK_MIGRATION_RU.txt",
  "docs/ARCADE_REACT_VITE_PHASE53_ARCHITECTURE_RULES_RU.txt",
  "docs/ARCADE_NEXT_GAME_CONCEPTS_RU.md",
  "docs/arcade_concepts/*.svg",
];

export const ARCADE_ARCHITECTURE_RULES: string[] = [
  "Arcade UI and in-game text stay English-only.",
  "React + Vite owns the route, while the canvas runtime remains a temporary fallback until each older game is retired.",
  "Both arcade.js copies stay aligned until the bridge layer is fully removed.",
  "Pro bridge games can keep local resume now, while cloud saves stay disabled in this archive.",
  "Canvas and React modules should write into the same runtime adapter layer until cloud sync is turned on.",
  "All new games should land directly as React modules and launch from React-owned controls.",
  "Runtime status should prefer shared runtime adapter events first, with DOM observing only as a backup for the shrinking canvas layer.",
  "Bridge game selection should live in runtimeAdapter state first, with older DOM controls mirrored only when needed.",
  "Bridge launch and restart requests should move through runtimeAdapter state/events first, with older buttons used only as fallback targets when available.",
  "Bridge boot readiness, queue state, runtime labels, control hints, selection notes, surface notes, progress notes, upgrade hints, overview notes, diagnostics summaries, route descriptions, and resume summaries should stay in runtimeAdapter so the page stays React-owned while the canvas layer shrinks.",
  "Keep a full handoff checklist, setup note, status snapshot, and 3 new-chat TXT files inside every archive so a new chat can resume from the latest phase immediately.",
  "React Free should stay capped at 5 games with one obvious showcase-quality hook, while the strongest depth-heavy modules stay positioned in Pro.",
  "Use a clearly sectioned shelf model in the page layer: Free shelf, Top Pro shelf, then Extended Pro, so monetization stays obvious without re-expanding fallback canvas UI.",
  "Supabase runtime sync should stay OFF in this archive, but the ready-to-wire TS helper and SQL scaffold can stay bundled for later repo work.",
];
