#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.join(__dirname, '..');
const LOCALES_DIR = path.join(ROOT, 'shared', 'i18n', 'locales');
const META_PATH = path.join(ROOT, 'shared', 'i18n', 'meta.json');
const JS_OUT = path.join(ROOT, 'public', 'i18n', 'siteI18n.js');
const FRONTEND_PUBLIC_JS_OUT = path.join(ROOT, 'frontend', 'public', 'i18n', 'siteI18n.js');
const EXTENSION_I18N_OUT = path.join(ROOT, 'extension', 'i18n-bundle.js');
const BRIDGE_JS_OUT = path.join(ROOT, 'public', 'bridge', 'i18n', 'siteI18n.js');
const REPORT_OUT = path.join(ROOT, 'docs', 'I18N_SYNC_REPORT.txt');

const DEFAULT_ORDER = ['en','de','fr','es','pt','it','nl','tr','pl','id','ru','uk','hi','ja','zh'];
const LOCALE_RE = /^[a-z]{2}$/;

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function writeJson(filePath, value) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(value, null, 2) + '\n', 'utf8');
}

function deepClone(value) {
  return JSON.parse(JSON.stringify(value));
}

function normalizeValue(base, current) {
  if (Array.isArray(base)) {
    const out = Array.isArray(current) ? current.slice(0, base.length) : [];
    for (let i = 0; i < base.length; i++) out[i] = normalizeValue(base[i], out[i]);
    return out;
  }
  if (base && typeof base === 'object') {
    const source = current && typeof current === 'object' && !Array.isArray(current) ? current : {};
    const out = {};
    for (const key of Object.keys(base)) out[key] = normalizeValue(base[key], source[key]);
    return out;
  }
  if (current === undefined || current === null || current === '') return deepClone(base);
  return current;
}

function collectStats(base, current, prefix = '', stats = { total: 0, copiedFromEn: 0, identicalToEn: 0 }) {
  if (Array.isArray(base)) {
    for (let i = 0; i < base.length; i++) {
      collectStats(base[i], Array.isArray(current) ? current[i] : undefined, `${prefix}[${i}]`, stats);
    }
    return stats;
  }
  if (base && typeof base === 'object') {
    const cur = current && typeof current === 'object' && !Array.isArray(current) ? current : {};
    for (const key of Object.keys(base)) {
      collectStats(base[key], cur[key], prefix ? `${prefix}.${key}` : key, stats);
    }
    return stats;
  }
  stats.total += 1;
  if (current === undefined || current === null || current === '') stats.copiedFromEn += 1;
  if (JSON.stringify(base) === JSON.stringify(current)) stats.identicalToEn += 1;
  return stats;
}

function makeJs(catalog) {
  const json = JSON.stringify(catalog, null, 2);
  return `/* Auto-generated by tools/i18n_sync.mjs. Do not edit by hand. */\n(function(root){\n  const SITE_I18N = ${json};\n  function clone(value){ return JSON.parse(JSON.stringify(value)); }\n  root.GMX_SITE_I18N = {\n    SITE_I18N,\n    createSiteI18nCatalog: function(){ return clone(SITE_I18N); }\n  };\n})(globalThis);\n`;
}

function main() {
  if (!fs.existsSync(LOCALES_DIR)) throw new Error(`Locales directory not found: ${LOCALES_DIR}`);

  const localeFiles = fs.readdirSync(LOCALES_DIR)
    .filter(name => name.endsWith('.json'))
    .map(name => name.slice(0, -5))
    .filter(code => LOCALE_RE.test(code));

  if (!localeFiles.includes('en')) throw new Error('shared/i18n/locales/en.json is required');

  const order = [
    ...DEFAULT_ORDER.filter(code => localeFiles.includes(code)),
    ...localeFiles.filter(code => !DEFAULT_ORDER.includes(code)).sort()
  ];

  const base = readJson(path.join(LOCALES_DIR, 'en.json'));
  const normalizedCatalog = {};
  const reportLines = [];

  reportLines.push('GMXReply i18n sync report');
  reportLines.push(`Updated: ${new Date().toISOString()}`);
  reportLines.push(`Locales: ${order.join(', ')}`);
  reportLines.push('');

  for (const code of order) {
    const filePath = path.join(LOCALES_DIR, `${code}.json`);
    const raw = readJson(filePath);
    const stats = collectStats(base, raw);
    const normalized = normalizeValue(base, raw);
    normalizedCatalog[code] = normalized;
    writeJson(filePath, normalized);
    const pct = stats.total ? Math.round((stats.identicalToEn / stats.total) * 100) : 0;
    reportLines.push(`${code}: copied-from-en=${stats.copiedFromEn}, identical-to-en=${stats.identicalToEn}/${stats.total} (${pct}%)`);
  }

  const meta = {
    version: 1,
    source: 'shared/i18n/locales/*.json',
    locales: order,
    generatedAt: new Date().toISOString()
  };
  writeJson(META_PATH, meta);

  fs.mkdirSync(path.dirname(JS_OUT), { recursive: true });
  const jsPayload = makeJs(normalizedCatalog);
  fs.writeFileSync(JS_OUT, jsPayload, 'utf8');
  fs.mkdirSync(path.dirname(FRONTEND_PUBLIC_JS_OUT), { recursive: true });
  fs.writeFileSync(FRONTEND_PUBLIC_JS_OUT, jsPayload, 'utf8');
  fs.mkdirSync(path.dirname(EXTENSION_I18N_OUT), { recursive: true });
  fs.writeFileSync(EXTENSION_I18N_OUT, jsPayload, 'utf8');
  fs.mkdirSync(path.dirname(BRIDGE_JS_OUT), { recursive: true });
  fs.writeFileSync(BRIDGE_JS_OUT, jsPayload, 'utf8');
  fs.mkdirSync(path.dirname(REPORT_OUT), { recursive: true });
  fs.writeFileSync(REPORT_OUT, reportLines.join('\n') + '\n', 'utf8');

  console.log(`Synced ${order.length} locales.`);
  console.log(`Wrote ${JS_OUT}`);
  console.log(`Wrote ${FRONTEND_PUBLIC_JS_OUT}`);
  console.log(`Wrote ${EXTENSION_I18N_OUT}`);
  console.log(`Wrote ${BRIDGE_JS_OUT}`);
}

main();
