// ---------- AUTH ----------
import { createAuth } from "./server/auth.mjs";

const {
  AUTH_COOKIE_NAME,
  AUTH_COOKIE_MAX_AGE_SEC,
  getAuthToken,
  setAuthCookie,
  getBearer,
  userByHandle,
  userByToken,
  requireAuth,
  maybeAuth,
  ensureUser,
  rotateToken,
  referralFingerprint,
  getReferralPromoterSummary,
  awardReferralBonus,
  getDailyLimit,
  referralRewardTotal,
  hasReferralReward,
  grantReferralReward,
  maybeAwardStarterReward,
  mapReferralNotCountedReason,
  classifyReferralEntry,
  computeReferralUnlocks,
  subscriptionInfo,
  insertLimitForUser,
} = createAuth({
  safeDb,
  db,
  nowIso,
  sendError,
  ERROR_CODES,
  normalizeHandle,
  validHandle,
  randHex,
  ADMIN_HANDLE_ENV,
  setAdminHandleCache: (value) => { ADMIN_HANDLE_CACHE = value; },
  CONFIG,
  supabaseActive,
  sbReferralsCount,
  sbRefClicksCount,
  referralCountConfirmed,
  referralCountActive,
  REF_MIN_ACTIVE_DAYS,
  REF_MIN_ACTIVE_USES,
  clientIp,
  sha256,
  isAdminHandle,
});
