import { createAdminGrants } from "./server/admin/grants.mjs";
import { registerAdminRoutes } from "./server/routes/admin.mjs";

const adminGrants = createAdminGrants({
  crypto,
  safeDb,
  db,
  nowIso,
  randHex,
  normalizeHandle,
  validHandle,
  ensureUser,
  userByHandle,
  subscriptionInfo,
  referralCountActive,
  referralRewardTotal,
  computeReferralUnlocks,
  grantReferralReward,
  logActivity,
});

var startAutoAwardsLoop;
({ startAutoAwardsLoop } = registerAdminRoutes({
  app,
  crypto,
  path,
  DB_PATH,
  BUILD_ID,
  STARTED_AT,
  ADMIN_SECRET,
  safeDb,
  db,
  nowIso,
  todayKeyUTC,
  randHex,
  getBearer,
  getAdminKey,
  getAdminToken,
  canUseDevAdminSession,
  adminSessionGet,
  userByToken,
  userByHandle,
  isAdminHandle,
  normalizeHandle,
  validHandle,
  ensureUser,
  subscriptionInfo,
  grantReferralReward,
  logActivity,
  ext: __GMX_EXT_SELECTORS,
  grants: adminGrants,
}));
